//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCopies.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCopies.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the About dialog box..
        /// </summary>
        public static string AboutStatusBarLabel {
            get {
                return ResourceManager.GetString("AboutStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have multiple windows open. Are you sure you want to close the application?.
        /// </summary>
        public static string ApplicationClosingMessage {
            get {
                return ResourceManager.GetString("ApplicationClosingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close _all tabs.
        /// </summary>
        public static string CloseAllTabs {
            get {
                return ResourceManager.GetString("CloseAllTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes all tabs..
        /// </summary>
        public static string CloseAllTabsStatusBarLabel {
            get {
                return ResourceManager.GetString("CloseAllTabsStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close other _tabs.
        /// </summary>
        public static string CloseOtherTabs {
            get {
                return ResourceManager.GetString("CloseOtherTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes all tabs but the current one..
        /// </summary>
        public static string CloseOtherTabsStatusBarLabel {
            get {
                return ResourceManager.GetString("CloseOtherTabsStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close tab.
        /// </summary>
        public static string CloseTab {
            get {
                return ResourceManager.GetString("CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the current tab..
        /// </summary>
        public static string CloseTabStatusBarLabel {
            get {
                return ResourceManager.GetString("CloseTabStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close _window.
        /// </summary>
        public static string CloseWindow {
            get {
                return ResourceManager.GetString("CloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the window..
        /// </summary>
        public static string CloseWindowStatusBarLabel {
            get {
                return ResourceManager.GetString("CloseWindowStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies the selected items to the Clipboard..
        /// </summary>
        public static string CopyStatusBarLabel {
            get {
                return ResourceManager.GetString("CopyStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies the selected items to the Clipboard and mark them for move..
        /// </summary>
        public static string CutStatusBarLabel {
            get {
                return ResourceManager.GetString("CutStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the selected items permanently..
        /// </summary>
        public static string DeleteStatusBarLabel {
            get {
                return ResourceManager.GetString("DeleteStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\deff0{\fonttbl{\f0 \fswiss Helvetica;}{\f1 Courier;}}
        ///{\colortbl;\red255\green0\blue0;\red0\green0\blue255;}
        ///\widowctrl\hyphauto
        ///
        ///{\pard \ql \f0 \sa180 \li0 \fi0 \b \fs28 GNU GENERAL PUBLIC LICENSE\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 Version 3, 29 June 2007\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 Copyright \u169? 2007 Free Software Foundation, Inc. &lt;{\field{\*\fldinst{HYPERLINK &quot;https://fsf.org/&quot;}}{\fldrslt{\ul
        ///https://fsf.org/
        ///}}}
        ///&gt;\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 Everyone is permi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gpl_3_0 {
            get {
                return ResourceManager.GetString("gpl_3_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file system tab.
        /// </summary>
        public static string NewFileSystemTab {
            get {
                return ResourceManager.GetString("NewFileSystemTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a new tab for file system browsing..
        /// </summary>
        public static string NewFileSystemTabStatusBarLabel {
            get {
                return ResourceManager.GetString("NewFileSystemTabStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New registry tab.
        /// </summary>
        public static string NewRegistryTab {
            get {
                return ResourceManager.GetString("NewRegistryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a new tab for Registry browsing..
        /// </summary>
        public static string NewRegistryTabStatusBarLabel {
            get {
                return ResourceManager.GetString("NewRegistryTabStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New tab.
        /// </summary>
        public static string NewTab {
            get {
                return ResourceManager.GetString("NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a new tab..
        /// </summary>
        public static string NewTabStatusBarLabel {
            get {
                return ResourceManager.GetString("NewTabStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New _window....
        /// </summary>
        public static string NewWindow {
            get {
                return ResourceManager.GetString("NewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a new window..
        /// </summary>
        public static string NewWindowStatusBarLabel {
            get {
                return ResourceManager.GetString("NewWindowStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New WMI tab.
        /// </summary>
        public static string NewWMITab {
            get {
                return ResourceManager.GetString("NewWMITab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a new tab for WMI browsing..
        /// </summary>
        public static string NewWMITabStatusBarLabel {
            get {
                return ResourceManager.GetString("NewWMITabStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastes the Clipboard items in the selected folder..
        /// </summary>
        public static string PasteStatusBarLabel {
            get {
                return ResourceManager.GetString("PasteStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes all windows of the current process..
        /// </summary>
        public static string QuitStatusBarLabel {
            get {
                return ResourceManager.GetString("QuitStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clipboard operation did not succeeded..
        /// </summary>
        public static string SetClipboardErrorMessage {
            get {
                return ResourceManager.GetString("SetClipboardErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a _bug....
        /// </summary>
        public static string SubmitABug {
            get {
                return ResourceManager.GetString("SubmitABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens your default browser at the WinCopies&apos; GitHub page..
        /// </summary>
        public static string SubmitABugStatusBarLabel {
            get {
                return ResourceManager.GetString("SubmitABugStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have multiple tabs open. Are you sure you want to close the window?.
        /// </summary>
        public static string WindowClosingMessage {
            get {
                return ResourceManager.GetString("WindowClosingMessage", resourceCulture);
            }
        }
    }
}
