//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCopies.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCopies.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the About dialog box..
        /// </summary>
        internal static string AboutStatusBarLabel {
            get {
                return ResourceManager.GetString("AboutStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have multiple windows open. Are you sure you want to close the application?.
        /// </summary>
        internal static string ApplicationClosingMessage {
            get {
                return ResourceManager.GetString("ApplicationClosingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close _all tabs.
        /// </summary>
        internal static string CloseAllTabs {
            get {
                return ResourceManager.GetString("CloseAllTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes all tabs..
        /// </summary>
        internal static string CloseAllTabsStatusBarLabel {
            get {
                return ResourceManager.GetString("CloseAllTabsStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close other _tabs.
        /// </summary>
        internal static string CloseOtherTabs {
            get {
                return ResourceManager.GetString("CloseOtherTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes all tabs but the current one..
        /// </summary>
        internal static string CloseOtherTabsStatusBarLabel {
            get {
                return ResourceManager.GetString("CloseOtherTabsStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close tab.
        /// </summary>
        internal static string CloseTab {
            get {
                return ResourceManager.GetString("CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the current tab..
        /// </summary>
        internal static string CloseTabStatusBarLabel {
            get {
                return ResourceManager.GetString("CloseTabStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close _window.
        /// </summary>
        internal static string CloseWindow {
            get {
                return ResourceManager.GetString("CloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the window..
        /// </summary>
        internal static string CloseWindowStatusBarLabel {
            get {
                return ResourceManager.GetString("CloseWindowStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\deff0{\fonttbl{\f0 \fswiss Helvetica;}{\f1 Courier;}}
        ///{\colortbl;\red255\green0\blue0;\red0\green0\blue255;}
        ///\widowctrl\hyphauto
        ///
        ///{\pard \ql \f0 \sa180 \li0 \fi0 \b \fs28 GNU GENERAL PUBLIC LICENSE\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 Version 3, 29 June 2007\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 Copyright \u169? 2007 Free Software Foundation, Inc. &lt;{\field{\*\fldinst{HYPERLINK &quot;https://fsf.org/&quot;}}{\fldrslt{\ul
        ///https://fsf.org/
        ///}}}
        ///&gt;\par}
        ///{\pard \ql \f0 \sa180 \li0 \fi0 Everyone is permitted to co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gpl_3_0 {
            get {
                return ResourceManager.GetString("gpl_3_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;menus&gt;
        ///  &lt;menu Resource=&quot;File&quot;&gt;
        ///    &lt;menu Resource=&quot;NewTab&quot; /&gt;
        ///    &lt;menu Resource=&quot;NewWindow&quot; /&gt;
        ///    &lt;menu Resource=&quot;CloseTab&quot; /&gt;
        ///    &lt;menu Resource=&quot;CloseOtherTabs&quot; /&gt;
        ///    &lt;menu Resource=&quot;CloseAllTabs&quot; /&gt;
        ///    &lt;menu Resource=&quot;CloseWindow&quot; /&gt;
        ///    &lt;menu Resource=&quot;Quit&quot; /&gt;
        ///  &lt;/menu&gt;
        ///  &lt;menu Resource=&quot;Help&quot;&gt;
        ///    &lt;menu Resource=&quot;About&quot; /&gt;
        ///    &lt;menu Resource=&quot;SubmitABug&quot; /&gt;
        ///  &lt;/menu&gt;
        ///&lt;/menus&gt;
        ///.
        /// </summary>
        internal static string Menus {
            get {
                return ResourceManager.GetString("Menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New tab.
        /// </summary>
        internal static string NewTab {
            get {
                return ResourceManager.GetString("NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens new tab..
        /// </summary>
        internal static string NewTabStatusBarLabel {
            get {
                return ResourceManager.GetString("NewTabStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New _window....
        /// </summary>
        internal static string NewWindow {
            get {
                return ResourceManager.GetString("NewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens new window..
        /// </summary>
        internal static string NewWindowStatusBarLabel {
            get {
                return ResourceManager.GetString("NewWindowStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes all windows of the current process..
        /// </summary>
        internal static string QuitStatusBarLabel {
            get {
                return ResourceManager.GetString("QuitStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a _bug....
        /// </summary>
        internal static string SubmitABug {
            get {
                return ResourceManager.GetString("SubmitABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens your default browser at the WinCopies&apos; GitHub page..
        /// </summary>
        internal static string SubmitABugStatusBarLabel {
            get {
                return ResourceManager.GetString("SubmitABugStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have multiple tabs open. Are you sure you want to close the window?.
        /// </summary>
        internal static string WindowClosingMessage {
            get {
                return ResourceManager.GetString("WindowClosingMessage", resourceCulture);
            }
        }
    }
}
